apiVersion: v1
kind: Pod
metadata:
  name: registry-image-consumer
spec:
  containers:
    - name: consumer
      image: fedora
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: registry-image-datavolume

