apiVersion: v1
kind: Pod
metadata:
  name: test-lookup
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
spec:
  containers:
  - name: test
    image: test-img:latest
    command: ["sleep", "10"]
